apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-nodejs-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      todo: api
  template:
    metadata:
      labels:
        todo: api
    spec:
      containers:
        - name: todo-api
          image: artursilveiradev/docker-k8s-nodejs-sample
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: todo-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    todo: api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
